name: CI
on:
  push:
    branch:
      tags-ignore:
        - v[0-9]+\.[0-9]+\.[0-9]+
    pull_request:

jobs:
  test:
    env :
      GO111MODULE: on
    strategy:
      fail-fast: false
      matrix:
        go: [1.14.x, 1.15.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: golangci/golangci-lint-action@v2

      - name: Run tests
        run: go test -run=. -race -v -covermode=atomic -coverprofile=./coverage.txt ./...

      - name: Upload linux coverage to Codecov
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: codecov/codecov-action@v1
        with:
          env_vars: os,go
          file: ./coverage.txt
