name: CI
on: [push, pull_request]

jobs:
  test:
    env :
      GO111MODULE: on
    strategy:
      fail-fast: false
      matrix:
        go: [1.15.x, 1.16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: golangci/golangci-lint-action@v2

      - name: Run tests
        run: go test -run=. -race -v -covermode=atomic -coverprofile=./coverage.txt ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        env:
          OS: ${{ matrix.os }}
          GO: ${{ matrix.go }}
        with:
          env_vars: OS,GO
          files: ./coverage.txt
          flags: unittests
          verbose: false
